//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPC_POS.Web.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPC_POS.Web.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System Exception. Please contact system administrator..
        /// </summary>
        public static string BCE000
        {
            get
            {
                return ResourceManager.GetString("BCE000", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incorrect Username or Password. Please input the correct details and try again..
        /// </summary>
        public static string BCE001
        {
            get
            {
                return ResourceManager.GetString("BCE001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked out for {0} minutes due to multiple failed login attempts..
        /// </summary>
        public static string BCE002
        {
            get
            {
                return ResourceManager.GetString("BCE002", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials. You have {0} more attempt(s) before your account gets locked out..
        /// </summary>
        public static string BCE003
        {
            get
            {
                return ResourceManager.GetString("BCE003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User Group &quot;{0}&quot; already exists..
        /// </summary>
        public static string BCE004
        {
            get
            {
                return ResourceManager.GetString("BCE004", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters and has followings conditions.&lt;br/&gt;
        ///1. Uppercase letter (A-Z)&lt;br/&gt;
        ///2. Lowercase letter (a-z)&lt;br/&gt;
        ///3. Number (0-9)&lt;br/&gt;
        ///4. Special character e.g. @, #, $, %, &amp; etc..
        /// </summary>
        public static string BCE005
        {
            get
            {
                return ResourceManager.GetString("BCE005", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot create user. Please contact system administrator..
        /// </summary>
        public static string BCE006
        {
            get
            {
                return ResourceManager.GetString("BCE006", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theatre and Session already exist, Please check first..
        /// </summary>
        public static string BCE007
        {
            get
            {
                return ResourceManager.GetString("BCE007", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot change Movie Type, Release Date, or Apper On. Please remove all revenue data before change it..
        /// </summary>
        public static string BCE008
        {
            get
            {
                return ResourceManager.GetString("BCE008", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot set appear  on &quot;Trailer&quot;, because release date less than or equal with current date. .
        /// </summary>
        public static string BCE009
        {
            get
            {
                return ResourceManager.GetString("BCE009", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password has expired, Please change your password first..
        /// </summary>
        public static string BCE010
        {
            get
            {
                return ResourceManager.GetString("BCE010", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this movie, Please remove all revenue data first..
        /// </summary>
        public static string BCE011
        {
            get
            {
                return ResourceManager.GetString("BCE011", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GPO is not related to Adms.&lt;br/&gt;Are you sure to save this data?.
        /// </summary>
        public static string BCE012
        {
            get
            {
                return ResourceManager.GetString("BCE012", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already send revenue by System/Sound, Cannot send preliminary again..
        /// </summary>
        public static string BCE013
        {
            get
            {
                return ResourceManager.GetString("BCE013", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System / Sound already exist, Please check first..
        /// </summary>
        public static string BCE014
        {
            get
            {
                return ResourceManager.GetString("BCE014", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot set status to &quot;Terminated&quot; because there is preliminary box office data in the system.&lt;br/&gt;
        ///Please set all box office status to &quot;Actual&quot; fist..
        /// </summary>
        public static string BCE015
        {
            get
            {
                return ResourceManager.GetString("BCE015", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot set status to &quot;Not release&quot; because there is box office data in the system.&lt;br/&gt;
        ///Please delete all box office data first..
        /// </summary>
        public static string BCE016
        {
            get
            {
                return ResourceManager.GetString("BCE016", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters and compose of at least two of followings conditions.&lt;br/&gt;
        ///1. Uppercase letter (A-Z)&lt;br/&gt;
        ///2. Lowercase letter (a-z)&lt;br/&gt;
        ///3. Number (0-9)&lt;br/&gt;
        ///4. Special character e.g. @, #, $, %, &amp; etc..
        /// </summary>
        public static string BCE017
        {
            get
            {
                return ResourceManager.GetString("BCE017", resourceCulture);
            }
        }
    }
}
